const ADD_ITEM_VISIBLE = "ADD_ITEM_VISIBLE";
const ITEM_INFO_VISIBLE = "ITEM_INFO_VISIBLE";
const HISTORY_LIST_VISIBLE = "HISTORY_LIST_VISIBLE";
const HISTORY_ITEM_INFO_VISIBLE = "HISTORY_ITEM_INFO_VISIBLE";

export default {
	ADD_ITEM_VISIBLE,
	ITEM_INFO_VISIBLE,
	HISTORY_LIST_VISIBLE,
	HISTORY_ITEM_INFO_VISIBLE,
};
